const topSlaylists = [
  {
    category: "Youtube channel",
    title: "Top YouTube Channers About Pop Artists",
    tagline:
      "Explore the best channels featuring rising and popular pop artists",
    likes: 25,
    owner_id: "PopStarFan",
    date_created: "2024-03-15",
    date_last_modified: "2024-04-10",
    slaylist_id: "SL001",
  },
  {
    category: "Youtube channel",
    title: "Worst Rock Performance Reaction Channels",
    tagline: "Dive into channels with the most infamous reactions",
    likes: 12,
    owner_id: "RocknRolled",
    date_created: "2024-01-20",
    date_last_modified: "2024-04-01",
    slaylist_id: "SL002",
  },
  {
    category: "Youtube channel",
    title: "Best Jazz Review Channels",
    tagline: "Discover top channels that review and discuss jazz music",
    likes: 32,
    owner_id: "JazzEnthusiast",
    date_created: "2024-02-11",
    date_last_modified: "2024-04-05",
    slaylist_id: "SL003",
  },
  {
    category: "Youtube channel",
    title: "Top Indie Music Discovery Channels",
    tagline: "Find the best channels dedicated to uncovering indie gems",
    likes: 40,
    owner_id: "IndieLover",
    date_created: "2024-03-28",
    date_last_modified: "2024-04-12",
    slaylist_id: "SL004",
  },
  {
    category: "Youtube channel",
    title: "Best Electro Swing Dance Tutorials",
    tagline: "Step up your dance with the best electro swing dancers",
    likes: 37,
    owner_id: "SwingDancer",
    date_created: "2024-01-05",
    date_last_modified: "2024-03-23",
    slaylist_id: "SL005",
  },
  {
    category: "Youtube channel",
    title: "Top 5 Rap Critic Channels",
    tagline:
      "Critical takes on rap: the best channels breaking down the lyrics",
    likes: 5,
    owner_id: "HipHopCritic",
    date_created: "2024-02-25",
    date_last_modified: "2024-04-10",
    slaylist_id: "SL006",
  },
  {
    category: "Youtube channel",
    title: "Best Opera Vocal Technique Analysis",
    tagline: "Explore channels analyzing the techniques of top opera singers",
    likes: 19,
    owner_id: "OperaBuff",
    date_created: "2024-02-17",
    date_last_modified: "2024-04-02",
    slaylist_id: "SL007",
  },
  {
    category: "Youtube channel",
    title: "Top Classical Music Appreciation Vlogs",
    tagline: "Vlogs that delve deep into the beauty of classical music",
    likes: 27,
    owner_id: "ClassicalFan123",
    date_created: "2024-03-10",
    date_last_modified: "2024-04-12",
    slaylist_id: "SL008",
  },
  {
    category: "Youtube channel",
    title: "1980s Album Cover Parody Creators",
    tagline: "Laugh at parodies of the most famous 1980s album covers",
    likes: 18,
    owner_id: "RetroArtFan",
    date_created: "2024-01-14",
    date_last_modified: "2024-04-07",
    slaylist_id: "SL009",
  },
];

module.exports = topSlaylists;
