const topSlaylists = [
  {
    category: "Youtube channel",
    title: "Top 10 Emerging Pop Artists of 2024",
    tagline: "Discover the future pop sensations!",
    likes: 25,
    owner_id: "PopStarFan",
    date_created: "2024-03-15",
    date_last_modified: "2024-04-10",
  },
  {
    category: "Youtube channel",
    title: "Worst Rock Performances Ever",
    tagline: "A roundup of rock's most infamous live moments",
    likes: 12,
    owner_id: "RocknRolled",
    date_created: "2024-01-20",
    date_last_modified: "2024-04-01",
  },
  {
    category: "Youtube channel",
    title: "Best Jazz Albums of the 1990s",
    tagline: "Golden picks from a golden era",
    likes: 32,
    owner_id: "JazzEnthusiast",
    date_created: "2024-02-11",
    date_last_modified: "2024-04-05",
  },
  {
    category: "Youtube channel",
    title: "Top Indie Songs Playlist",
    tagline: "Indie treasures for your ears",
    likes: 40,
    owner_id: "IndieLover",
    date_created: "2024-03-28",
    date_last_modified: "2024-04-12",
  },
  {
    category: "Youtube channel",
    title: "Best of Electro Swing - Dance Edition",
    tagline: "Swing to modern beats",
    likes: 37,
    owner_id: "SwingDancer",
    date_created: "2024-01-05",
    date_last_modified: "2024-03-23",
  },
  {
    category: "Youtube channel",
    title: "Top 5 Worst Rap Lyrics",
    tagline: "What were they thinking?",
    likes: 5,
    owner_id: "HipHopCritic",
    date_created: "2024-02-25",
    date_last_modified: "2024-04-10",
  },
  {
    category: "Youtube channel",
    title: "Best Vocal Performances in Opera",
    tagline: "Voices that defy expectations",
    likes: 19,
    owner_id: "OperaBuff",
    date_created: "2024-02-17",
    date_last_modified: "2024-04-02",
  },
  {
    category: "Youtube channel",
    title: "Top Classical Composers of All Time",
    tagline: "Masters of melody and emotion",
    likes: 27,
    owner_id: "ClassicalFan123",
    date_created: "2024-03-10",
    date_last_modified: "2024-04-12",
  },
  {
    category: "Youtube channel",
    title: "Worst Album Covers of the 1980s",
    tagline: "A visual journey through some questionable choices",
    likes: 18,
    owner_id: "RetroArtFan",
    date_created: "2024-01-14",
    date_last_modified: "2024-04-07",
  },
  {
    category: "Youtube channel",
    title: "Best Guitar Solos of All Time",
    tagline: "Epic riffs that shaped rock history",
    likes: 33,
    owner_id: "GuitarGods",
    date_created: "2024-02-03",
    date_last_modified: "2024-04-11",
  },
  {
    category: "Youtube channel",
    title: "Top 10 Most Influential Techno Tracks",
    tagline: "Beats that defined a genre",
    likes: 29,
    owner_id: "TechnoMaster",
    date_created: "2024-01-30",
    date_last_modified: "2024-04-09",
  },
  {
    category: "Youtube channel",
    title: "Worst Pop Song Lyrics of 2023",
    tagline: "When words don’t quite hit the mark",
    likes: 7,
    owner_id: "LyricCritic",
    date_created: "2024-03-01",
    date_last_modified: "2024-04-05",
  },
  {
    category: "Youtube channel",
    title: "Best Upcoming Folk Artists to Watch",
    tagline: "Folk’s future stars in the making",
    likes: 23,
    owner_id: "FolkFanatic",
    date_created: "2024-03-22",
    date_last_modified: "2024-04-08",
  },
  {
    category: "Youtube channel",
    title: "Top Violin Performances in Film Scores",
    tagline: "Iconic strings that moved the cinema",
    likes: 35,
    owner_id: "CineMusicLover",
    date_created: "2024-03-15",
    date_last_modified: "2024-04-03",
  },
  {
    category: "Youtube channel",
    title: "Best Electronic Dance Music Drops",
    tagline: "Drops that drove crowds wild",
    likes: 26,
    owner_id: "EDMAddict",
    date_created: "2024-02-20",
    date_last_modified: "2024-04-12",
  },
];

module.exports = topSlaylists;
